### ISSUE TITLE
Overtemperature sense proposal

### ISSUE THREAD

**Issue by ghost** [makerspace-wi/Laser-Cutter-Engraver#2]
Stonie hat vorgeschlagen, PB3 vom Safety- und Marker Module zu nutzen um die Laser Temperatur gegen einen Schwellwert zu prüfen und bei erreichen den Laser abzuschalten.
Plan ist NTC plus Widerstand einzubauen und die Spannungsteilerspannung zu überwachen.

**Comment by dhaude** [comment]
nicht mehr aktuell
